// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package validatorx

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockValidator creates a new instance of MockValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockValidator {
	mock := &MockValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockValidator is an autogenerated mock type for the Validator type
type MockValidator struct {
	mock.Mock
}

type MockValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockValidator) EXPECT() *MockValidator_Expecter {
	return &MockValidator_Expecter{mock: &_m.Mock}
}

// ValidateStruct provides a mock function for the type MockValidator
func (_mock *MockValidator) ValidateStruct(data any) error {
	ret := _mock.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for ValidateStruct")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any) error); ok {
		r0 = returnFunc(data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockValidator_ValidateStruct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateStruct'
type MockValidator_ValidateStruct_Call struct {
	*mock.Call
}

// ValidateStruct is a helper method to define mock.On call
//   - data any
func (_e *MockValidator_Expecter) ValidateStruct(data interface{}) *MockValidator_ValidateStruct_Call {
	return &MockValidator_ValidateStruct_Call{Call: _e.mock.On("ValidateStruct", data)}
}

func (_c *MockValidator_ValidateStruct_Call) Run(run func(data any)) *MockValidator_ValidateStruct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockValidator_ValidateStruct_Call) Return(err error) *MockValidator_ValidateStruct_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockValidator_ValidateStruct_Call) RunAndReturn(run func(data any) error) *MockValidator_ValidateStruct_Call {
	_c.Call.Return(run)
	return _c
}
