all: false
dir: "{{.InterfaceDir}}"
pkgname: "{{.SrcPackageName}}"
packages:
  ./internal/app/domain/repository:
    config:
      recursive: True
      all: True
      filename: "{{.InterfaceName | snakecase}}_mock.go"
  ./pkg:
    config:
      recursive: True
      all: True
      filename: "mock.go"
