// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package jwtx

import (
	"time"

	"github.com/gofiber/fiber/v2"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClaims creates a new instance of MockClaims. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClaims(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClaims {
	mock := &MockClaims{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClaims is an autogenerated mock type for the Claims type
type MockClaims struct {
	mock.Mock
}

type MockClaims_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClaims) EXPECT() *MockClaims_Expecter {
	return &MockClaims_Expecter{mock: &_m.Mock}
}

// GetID provides a mock function for the type MockClaims
func (_mock *MockClaims) GetID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockClaims_GetID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetID'
type MockClaims_GetID_Call struct {
	*mock.Call
}

// GetID is a helper method to define mock.On call
func (_e *MockClaims_Expecter) GetID() *MockClaims_GetID_Call {
	return &MockClaims_GetID_Call{Call: _e.mock.On("GetID")}
}

func (_c *MockClaims_GetID_Call) Run(run func()) *MockClaims_GetID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClaims_GetID_Call) Return(s string) *MockClaims_GetID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockClaims_GetID_Call) RunAndReturn(run func() string) *MockClaims_GetID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJwt creates a new instance of MockJwt. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJwt(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJwt {
	mock := &MockJwt{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJwt is an autogenerated mock type for the Jwt type
type MockJwt struct {
	mock.Mock
}

type MockJwt_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJwt) EXPECT() *MockJwt_Expecter {
	return &MockJwt_Expecter{mock: &_m.Mock}
}

// CreateStandardClaims provides a mock function for the type MockJwt
func (_mock *MockJwt) CreateStandardClaims(id string, expireTime time.Duration) StandardClaims {
	ret := _mock.Called(id, expireTime)

	if len(ret) == 0 {
		panic("no return value specified for CreateStandardClaims")
	}

	var r0 StandardClaims
	if returnFunc, ok := ret.Get(0).(func(string, time.Duration) StandardClaims); ok {
		r0 = returnFunc(id, expireTime)
	} else {
		r0 = ret.Get(0).(StandardClaims)
	}
	return r0
}

// MockJwt_CreateStandardClaims_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateStandardClaims'
type MockJwt_CreateStandardClaims_Call struct {
	*mock.Call
}

// CreateStandardClaims is a helper method to define mock.On call
//   - id string
//   - expireTime time.Duration
func (_e *MockJwt_Expecter) CreateStandardClaims(id interface{}, expireTime interface{}) *MockJwt_CreateStandardClaims_Call {
	return &MockJwt_CreateStandardClaims_Call{Call: _e.mock.On("CreateStandardClaims", id, expireTime)}
}

func (_c *MockJwt_CreateStandardClaims_Call) Run(run func(id string, expireTime time.Duration)) *MockJwt_CreateStandardClaims_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJwt_CreateStandardClaims_Call) Return(standardClaims StandardClaims) *MockJwt_CreateStandardClaims_Call {
	_c.Call.Return(standardClaims)
	return _c
}

func (_c *MockJwt_CreateStandardClaims_Call) RunAndReturn(run func(id string, expireTime time.Duration) StandardClaims) *MockJwt_CreateStandardClaims_Call {
	_c.Call.Return(run)
	return _c
}

// ExtractTokenFromHeader provides a mock function for the type MockJwt
func (_mock *MockJwt) ExtractTokenFromHeader(c *fiber.Ctx) (string, error) {
	ret := _mock.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for ExtractTokenFromHeader")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*fiber.Ctx) (string, error)); ok {
		return returnFunc(c)
	}
	if returnFunc, ok := ret.Get(0).(func(*fiber.Ctx) string); ok {
		r0 = returnFunc(c)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(*fiber.Ctx) error); ok {
		r1 = returnFunc(c)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJwt_ExtractTokenFromHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtractTokenFromHeader'
type MockJwt_ExtractTokenFromHeader_Call struct {
	*mock.Call
}

// ExtractTokenFromHeader is a helper method to define mock.On call
//   - c *fiber.Ctx
func (_e *MockJwt_Expecter) ExtractTokenFromHeader(c interface{}) *MockJwt_ExtractTokenFromHeader_Call {
	return &MockJwt_ExtractTokenFromHeader_Call{Call: _e.mock.On("ExtractTokenFromHeader", c)}
}

func (_c *MockJwt_ExtractTokenFromHeader_Call) Run(run func(c *fiber.Ctx)) *MockJwt_ExtractTokenFromHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *fiber.Ctx
		if args[0] != nil {
			arg0 = args[0].(*fiber.Ctx)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockJwt_ExtractTokenFromHeader_Call) Return(s string, err error) *MockJwt_ExtractTokenFromHeader_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockJwt_ExtractTokenFromHeader_Call) RunAndReturn(run func(c *fiber.Ctx) (string, error)) *MockJwt_ExtractTokenFromHeader_Call {
	_c.Call.Return(run)
	return _c
}

// Generate provides a mock function for the type MockJwt
func (_mock *MockJwt) Generate(claims interface{}, secret string) (string, error) {
	ret := _mock.Called(claims, secret)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(interface{}, string) (string, error)); ok {
		return returnFunc(claims, secret)
	}
	if returnFunc, ok := ret.Get(0).(func(interface{}, string) string); ok {
		r0 = returnFunc(claims, secret)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(interface{}, string) error); ok {
		r1 = returnFunc(claims, secret)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJwt_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type MockJwt_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - claims interface{}
//   - secret string
func (_e *MockJwt_Expecter) Generate(claims interface{}, secret interface{}) *MockJwt_Generate_Call {
	return &MockJwt_Generate_Call{Call: _e.mock.On("Generate", claims, secret)}
}

func (_c *MockJwt_Generate_Call) Run(run func(claims interface{}, secret string)) *MockJwt_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 interface{}
		if args[0] != nil {
			arg0 = args[0].(interface{})
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJwt_Generate_Call) Return(s string, err error) *MockJwt_Generate_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockJwt_Generate_Call) RunAndReturn(run func(claims interface{}, secret string) (string, error)) *MockJwt_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// Parse provides a mock function for the type MockJwt
func (_mock *MockJwt) Parse(tokenString string, secret string, result interface{}) error {
	ret := _mock.Called(tokenString, secret, result)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, interface{}) error); ok {
		r0 = returnFunc(tokenString, secret, result)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockJwt_Parse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parse'
type MockJwt_Parse_Call struct {
	*mock.Call
}

// Parse is a helper method to define mock.On call
//   - tokenString string
//   - secret string
//   - result interface{}
func (_e *MockJwt_Expecter) Parse(tokenString interface{}, secret interface{}, result interface{}) *MockJwt_Parse_Call {
	return &MockJwt_Parse_Call{Call: _e.mock.On("Parse", tokenString, secret, result)}
}

func (_c *MockJwt_Parse_Call) Run(run func(tokenString string, secret string, result interface{})) *MockJwt_Parse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 interface{}
		if args[2] != nil {
			arg2 = args[2].(interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockJwt_Parse_Call) Return(err error) *MockJwt_Parse_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockJwt_Parse_Call) RunAndReturn(run func(tokenString string, secret string, result interface{}) error) *MockJwt_Parse_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateToken provides a mock function for the type MockJwt
func (_mock *MockJwt) ValidateToken(tokenString string, secret string) error {
	ret := _mock.Called(tokenString, secret)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(tokenString, secret)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockJwt_ValidateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateToken'
type MockJwt_ValidateToken_Call struct {
	*mock.Call
}

// ValidateToken is a helper method to define mock.On call
//   - tokenString string
//   - secret string
func (_e *MockJwt_Expecter) ValidateToken(tokenString interface{}, secret interface{}) *MockJwt_ValidateToken_Call {
	return &MockJwt_ValidateToken_Call{Call: _e.mock.On("ValidateToken", tokenString, secret)}
}

func (_c *MockJwt_ValidateToken_Call) Run(run func(tokenString string, secret string)) *MockJwt_ValidateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJwt_ValidateToken_Call) Return(err error) *MockJwt_ValidateToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockJwt_ValidateToken_Call) RunAndReturn(run func(tokenString string, secret string) error) *MockJwt_ValidateToken_Call {
	_c.Call.Return(run)
	return _c
}
