// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package jwtx

import (
	"time"

	"github.com/gofiber/fiber/v2"
	"github.com/golang-jwt/jwt/v5"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClaims creates a new instance of MockClaims. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClaims(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClaims {
	mock := &MockClaims{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClaims is an autogenerated mock type for the Claims type
type MockClaims struct {
	mock.Mock
}

type MockClaims_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClaims) EXPECT() *MockClaims_Expecter {
	return &MockClaims_Expecter{mock: &_m.Mock}
}

// GetAudience provides a mock function for the type MockClaims
func (_mock *MockClaims) GetAudience() (jwt.ClaimStrings, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAudience")
	}

	var r0 jwt.ClaimStrings
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (jwt.ClaimStrings, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() jwt.ClaimStrings); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jwt.ClaimStrings)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClaims_GetAudience_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAudience'
type MockClaims_GetAudience_Call struct {
	*mock.Call
}

// GetAudience is a helper method to define mock.On call
func (_e *MockClaims_Expecter) GetAudience() *MockClaims_GetAudience_Call {
	return &MockClaims_GetAudience_Call{Call: _e.mock.On("GetAudience")}
}

func (_c *MockClaims_GetAudience_Call) Run(run func()) *MockClaims_GetAudience_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClaims_GetAudience_Call) Return(claimStrings jwt.ClaimStrings, err error) *MockClaims_GetAudience_Call {
	_c.Call.Return(claimStrings, err)
	return _c
}

func (_c *MockClaims_GetAudience_Call) RunAndReturn(run func() (jwt.ClaimStrings, error)) *MockClaims_GetAudience_Call {
	_c.Call.Return(run)
	return _c
}

// GetExpirationTime provides a mock function for the type MockClaims
func (_mock *MockClaims) GetExpirationTime() (*jwt.NumericDate, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetExpirationTime")
	}

	var r0 *jwt.NumericDate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*jwt.NumericDate, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *jwt.NumericDate); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jwt.NumericDate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClaims_GetExpirationTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExpirationTime'
type MockClaims_GetExpirationTime_Call struct {
	*mock.Call
}

// GetExpirationTime is a helper method to define mock.On call
func (_e *MockClaims_Expecter) GetExpirationTime() *MockClaims_GetExpirationTime_Call {
	return &MockClaims_GetExpirationTime_Call{Call: _e.mock.On("GetExpirationTime")}
}

func (_c *MockClaims_GetExpirationTime_Call) Run(run func()) *MockClaims_GetExpirationTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClaims_GetExpirationTime_Call) Return(numericDate *jwt.NumericDate, err error) *MockClaims_GetExpirationTime_Call {
	_c.Call.Return(numericDate, err)
	return _c
}

func (_c *MockClaims_GetExpirationTime_Call) RunAndReturn(run func() (*jwt.NumericDate, error)) *MockClaims_GetExpirationTime_Call {
	_c.Call.Return(run)
	return _c
}

// GetID provides a mock function for the type MockClaims
func (_mock *MockClaims) GetID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockClaims_GetID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetID'
type MockClaims_GetID_Call struct {
	*mock.Call
}

// GetID is a helper method to define mock.On call
func (_e *MockClaims_Expecter) GetID() *MockClaims_GetID_Call {
	return &MockClaims_GetID_Call{Call: _e.mock.On("GetID")}
}

func (_c *MockClaims_GetID_Call) Run(run func()) *MockClaims_GetID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClaims_GetID_Call) Return(s string) *MockClaims_GetID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockClaims_GetID_Call) RunAndReturn(run func() string) *MockClaims_GetID_Call {
	_c.Call.Return(run)
	return _c
}

// GetIssuedAt provides a mock function for the type MockClaims
func (_mock *MockClaims) GetIssuedAt() (*jwt.NumericDate, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetIssuedAt")
	}

	var r0 *jwt.NumericDate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*jwt.NumericDate, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *jwt.NumericDate); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jwt.NumericDate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClaims_GetIssuedAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIssuedAt'
type MockClaims_GetIssuedAt_Call struct {
	*mock.Call
}

// GetIssuedAt is a helper method to define mock.On call
func (_e *MockClaims_Expecter) GetIssuedAt() *MockClaims_GetIssuedAt_Call {
	return &MockClaims_GetIssuedAt_Call{Call: _e.mock.On("GetIssuedAt")}
}

func (_c *MockClaims_GetIssuedAt_Call) Run(run func()) *MockClaims_GetIssuedAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClaims_GetIssuedAt_Call) Return(numericDate *jwt.NumericDate, err error) *MockClaims_GetIssuedAt_Call {
	_c.Call.Return(numericDate, err)
	return _c
}

func (_c *MockClaims_GetIssuedAt_Call) RunAndReturn(run func() (*jwt.NumericDate, error)) *MockClaims_GetIssuedAt_Call {
	_c.Call.Return(run)
	return _c
}

// GetIssuer provides a mock function for the type MockClaims
func (_mock *MockClaims) GetIssuer() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetIssuer")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClaims_GetIssuer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIssuer'
type MockClaims_GetIssuer_Call struct {
	*mock.Call
}

// GetIssuer is a helper method to define mock.On call
func (_e *MockClaims_Expecter) GetIssuer() *MockClaims_GetIssuer_Call {
	return &MockClaims_GetIssuer_Call{Call: _e.mock.On("GetIssuer")}
}

func (_c *MockClaims_GetIssuer_Call) Run(run func()) *MockClaims_GetIssuer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClaims_GetIssuer_Call) Return(s string, err error) *MockClaims_GetIssuer_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockClaims_GetIssuer_Call) RunAndReturn(run func() (string, error)) *MockClaims_GetIssuer_Call {
	_c.Call.Return(run)
	return _c
}

// GetNotBefore provides a mock function for the type MockClaims
func (_mock *MockClaims) GetNotBefore() (*jwt.NumericDate, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetNotBefore")
	}

	var r0 *jwt.NumericDate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*jwt.NumericDate, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *jwt.NumericDate); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jwt.NumericDate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClaims_GetNotBefore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNotBefore'
type MockClaims_GetNotBefore_Call struct {
	*mock.Call
}

// GetNotBefore is a helper method to define mock.On call
func (_e *MockClaims_Expecter) GetNotBefore() *MockClaims_GetNotBefore_Call {
	return &MockClaims_GetNotBefore_Call{Call: _e.mock.On("GetNotBefore")}
}

func (_c *MockClaims_GetNotBefore_Call) Run(run func()) *MockClaims_GetNotBefore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClaims_GetNotBefore_Call) Return(numericDate *jwt.NumericDate, err error) *MockClaims_GetNotBefore_Call {
	_c.Call.Return(numericDate, err)
	return _c
}

func (_c *MockClaims_GetNotBefore_Call) RunAndReturn(run func() (*jwt.NumericDate, error)) *MockClaims_GetNotBefore_Call {
	_c.Call.Return(run)
	return _c
}

// GetSubject provides a mock function for the type MockClaims
func (_mock *MockClaims) GetSubject() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSubject")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClaims_GetSubject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubject'
type MockClaims_GetSubject_Call struct {
	*mock.Call
}

// GetSubject is a helper method to define mock.On call
func (_e *MockClaims_Expecter) GetSubject() *MockClaims_GetSubject_Call {
	return &MockClaims_GetSubject_Call{Call: _e.mock.On("GetSubject")}
}

func (_c *MockClaims_GetSubject_Call) Run(run func()) *MockClaims_GetSubject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClaims_GetSubject_Call) Return(s string, err error) *MockClaims_GetSubject_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockClaims_GetSubject_Call) RunAndReturn(run func() (string, error)) *MockClaims_GetSubject_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJwt creates a new instance of MockJwt. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJwt(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJwt {
	mock := &MockJwt{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJwt is an autogenerated mock type for the Jwt type
type MockJwt struct {
	mock.Mock
}

type MockJwt_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJwt) EXPECT() *MockJwt_Expecter {
	return &MockJwt_Expecter{mock: &_m.Mock}
}

// CreateStandardClaims provides a mock function for the type MockJwt
func (_mock *MockJwt) CreateStandardClaims(id string, expireTime time.Duration) StandardClaims {
	ret := _mock.Called(id, expireTime)

	if len(ret) == 0 {
		panic("no return value specified for CreateStandardClaims")
	}

	var r0 StandardClaims
	if returnFunc, ok := ret.Get(0).(func(string, time.Duration) StandardClaims); ok {
		r0 = returnFunc(id, expireTime)
	} else {
		r0 = ret.Get(0).(StandardClaims)
	}
	return r0
}

// MockJwt_CreateStandardClaims_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateStandardClaims'
type MockJwt_CreateStandardClaims_Call struct {
	*mock.Call
}

// CreateStandardClaims is a helper method to define mock.On call
//   - id string
//   - expireTime time.Duration
func (_e *MockJwt_Expecter) CreateStandardClaims(id interface{}, expireTime interface{}) *MockJwt_CreateStandardClaims_Call {
	return &MockJwt_CreateStandardClaims_Call{Call: _e.mock.On("CreateStandardClaims", id, expireTime)}
}

func (_c *MockJwt_CreateStandardClaims_Call) Run(run func(id string, expireTime time.Duration)) *MockJwt_CreateStandardClaims_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJwt_CreateStandardClaims_Call) Return(standardClaims StandardClaims) *MockJwt_CreateStandardClaims_Call {
	_c.Call.Return(standardClaims)
	return _c
}

func (_c *MockJwt_CreateStandardClaims_Call) RunAndReturn(run func(id string, expireTime time.Duration) StandardClaims) *MockJwt_CreateStandardClaims_Call {
	_c.Call.Return(run)
	return _c
}

// ExtractTokenFromHeader provides a mock function for the type MockJwt
func (_mock *MockJwt) ExtractTokenFromHeader(c *fiber.Ctx) (string, error) {
	ret := _mock.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for ExtractTokenFromHeader")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*fiber.Ctx) (string, error)); ok {
		return returnFunc(c)
	}
	if returnFunc, ok := ret.Get(0).(func(*fiber.Ctx) string); ok {
		r0 = returnFunc(c)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(*fiber.Ctx) error); ok {
		r1 = returnFunc(c)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJwt_ExtractTokenFromHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtractTokenFromHeader'
type MockJwt_ExtractTokenFromHeader_Call struct {
	*mock.Call
}

// ExtractTokenFromHeader is a helper method to define mock.On call
//   - c *fiber.Ctx
func (_e *MockJwt_Expecter) ExtractTokenFromHeader(c interface{}) *MockJwt_ExtractTokenFromHeader_Call {
	return &MockJwt_ExtractTokenFromHeader_Call{Call: _e.mock.On("ExtractTokenFromHeader", c)}
}

func (_c *MockJwt_ExtractTokenFromHeader_Call) Run(run func(c *fiber.Ctx)) *MockJwt_ExtractTokenFromHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *fiber.Ctx
		if args[0] != nil {
			arg0 = args[0].(*fiber.Ctx)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockJwt_ExtractTokenFromHeader_Call) Return(s string, err error) *MockJwt_ExtractTokenFromHeader_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockJwt_ExtractTokenFromHeader_Call) RunAndReturn(run func(c *fiber.Ctx) (string, error)) *MockJwt_ExtractTokenFromHeader_Call {
	_c.Call.Return(run)
	return _c
}

// Generate provides a mock function for the type MockJwt
func (_mock *MockJwt) Generate(claims Claims, secret string) (string, error) {
	ret := _mock.Called(claims, secret)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(Claims, string) (string, error)); ok {
		return returnFunc(claims, secret)
	}
	if returnFunc, ok := ret.Get(0).(func(Claims, string) string); ok {
		r0 = returnFunc(claims, secret)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(Claims, string) error); ok {
		r1 = returnFunc(claims, secret)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJwt_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type MockJwt_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - claims Claims
//   - secret string
func (_e *MockJwt_Expecter) Generate(claims interface{}, secret interface{}) *MockJwt_Generate_Call {
	return &MockJwt_Generate_Call{Call: _e.mock.On("Generate", claims, secret)}
}

func (_c *MockJwt_Generate_Call) Run(run func(claims Claims, secret string)) *MockJwt_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Claims
		if args[0] != nil {
			arg0 = args[0].(Claims)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJwt_Generate_Call) Return(s string, err error) *MockJwt_Generate_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockJwt_Generate_Call) RunAndReturn(run func(claims Claims, secret string) (string, error)) *MockJwt_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// Parse provides a mock function for the type MockJwt
func (_mock *MockJwt) Parse(tokenString string, claims jwt.Claims, secret string) (jwt.Claims, error) {
	ret := _mock.Called(tokenString, claims, secret)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 jwt.Claims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, jwt.Claims, string) (jwt.Claims, error)); ok {
		return returnFunc(tokenString, claims, secret)
	}
	if returnFunc, ok := ret.Get(0).(func(string, jwt.Claims, string) jwt.Claims); ok {
		r0 = returnFunc(tokenString, claims, secret)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jwt.Claims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, jwt.Claims, string) error); ok {
		r1 = returnFunc(tokenString, claims, secret)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJwt_Parse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parse'
type MockJwt_Parse_Call struct {
	*mock.Call
}

// Parse is a helper method to define mock.On call
//   - tokenString string
//   - claims jwt.Claims
//   - secret string
func (_e *MockJwt_Expecter) Parse(tokenString interface{}, claims interface{}, secret interface{}) *MockJwt_Parse_Call {
	return &MockJwt_Parse_Call{Call: _e.mock.On("Parse", tokenString, claims, secret)}
}

func (_c *MockJwt_Parse_Call) Run(run func(tokenString string, claims jwt.Claims, secret string)) *MockJwt_Parse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 jwt.Claims
		if args[1] != nil {
			arg1 = args[1].(jwt.Claims)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockJwt_Parse_Call) Return(claims1 jwt.Claims, err error) *MockJwt_Parse_Call {
	_c.Call.Return(claims1, err)
	return _c
}

func (_c *MockJwt_Parse_Call) RunAndReturn(run func(tokenString string, claims jwt.Claims, secret string) (jwt.Claims, error)) *MockJwt_Parse_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateToken provides a mock function for the type MockJwt
func (_mock *MockJwt) ValidateToken(tokenString string, claims jwt.Claims, secret string) error {
	ret := _mock.Called(tokenString, claims, secret)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, jwt.Claims, string) error); ok {
		r0 = returnFunc(tokenString, claims, secret)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockJwt_ValidateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateToken'
type MockJwt_ValidateToken_Call struct {
	*mock.Call
}

// ValidateToken is a helper method to define mock.On call
//   - tokenString string
//   - claims jwt.Claims
//   - secret string
func (_e *MockJwt_Expecter) ValidateToken(tokenString interface{}, claims interface{}, secret interface{}) *MockJwt_ValidateToken_Call {
	return &MockJwt_ValidateToken_Call{Call: _e.mock.On("ValidateToken", tokenString, claims, secret)}
}

func (_c *MockJwt_ValidateToken_Call) Run(run func(tokenString string, claims jwt.Claims, secret string)) *MockJwt_ValidateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 jwt.Claims
		if args[1] != nil {
			arg1 = args[1].(jwt.Claims)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockJwt_ValidateToken_Call) Return(err error) *MockJwt_ValidateToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockJwt_ValidateToken_Call) RunAndReturn(run func(tokenString string, claims jwt.Claims, secret string) error) *MockJwt_ValidateToken_Call {
	_c.Call.Return(run)
	return _c
}
