// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package redisx

import (
	"context"
	"time"

	"github.com/redis/go-redis/v9"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRedis creates a new instance of MockRedis. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRedis(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRedis {
	mock := &MockRedis{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRedis is an autogenerated mock type for the Redis type
type MockRedis struct {
	mock.Mock
}

type MockRedis_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRedis) EXPECT() *MockRedis_Expecter {
	return &MockRedis_Expecter{mock: &_m.Mock}
}

// Client provides a mock function for the type MockRedis
func (_mock *MockRedis) Client() *redis.Client {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Client")
	}

	var r0 *redis.Client
	if returnFunc, ok := ret.Get(0).(func() *redis.Client); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*redis.Client)
		}
	}
	return r0
}

// MockRedis_Client_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Client'
type MockRedis_Client_Call struct {
	*mock.Call
}

// Client is a helper method to define mock.On call
func (_e *MockRedis_Expecter) Client() *MockRedis_Client_Call {
	return &MockRedis_Client_Call{Call: _e.mock.On("Client")}
}

func (_c *MockRedis_Client_Call) Run(run func()) *MockRedis_Client_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRedis_Client_Call) Return(client *redis.Client) *MockRedis_Client_Call {
	_c.Call.Return(client)
	return _c
}

func (_c *MockRedis_Client_Call) RunAndReturn(run func() *redis.Client) *MockRedis_Client_Call {
	_c.Call.Return(run)
	return _c
}

// Del provides a mock function for the type MockRedis
func (_mock *MockRedis) Del(ctx context.Context, keys ...string) error {
	var tmpRet mock.Arguments
	if len(keys) > 0 {
		tmpRet = _mock.Called(ctx, keys)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Del")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) error); ok {
		r0 = returnFunc(ctx, keys...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRedis_Del_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Del'
type MockRedis_Del_Call struct {
	*mock.Call
}

// Del is a helper method to define mock.On call
//   - ctx context.Context
//   - keys ...string
func (_e *MockRedis_Expecter) Del(ctx interface{}, keys ...interface{}) *MockRedis_Del_Call {
	return &MockRedis_Del_Call{Call: _e.mock.On("Del",
		append([]interface{}{ctx}, keys...)...)}
}

func (_c *MockRedis_Del_Call) Run(run func(ctx context.Context, keys ...string)) *MockRedis_Del_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockRedis_Del_Call) Return(err error) *MockRedis_Del_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRedis_Del_Call) RunAndReturn(run func(ctx context.Context, keys ...string) error) *MockRedis_Del_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function for the type MockRedis
func (_mock *MockRedis) Exists(ctx context.Context, keys ...string) (bool, error) {
	var tmpRet mock.Arguments
	if len(keys) > 0 {
		tmpRet = _mock.Called(ctx, keys)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) (bool, error)); ok {
		return returnFunc(ctx, keys...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) bool); ok {
		r0 = returnFunc(ctx, keys...)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...string) error); ok {
		r1 = returnFunc(ctx, keys...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRedis_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockRedis_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - keys ...string
func (_e *MockRedis_Expecter) Exists(ctx interface{}, keys ...interface{}) *MockRedis_Exists_Call {
	return &MockRedis_Exists_Call{Call: _e.mock.On("Exists",
		append([]interface{}{ctx}, keys...)...)}
}

func (_c *MockRedis_Exists_Call) Run(run func(ctx context.Context, keys ...string)) *MockRedis_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockRedis_Exists_Call) Return(b bool, err error) *MockRedis_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockRedis_Exists_Call) RunAndReturn(run func(ctx context.Context, keys ...string) (bool, error)) *MockRedis_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockRedis
func (_mock *MockRedis) Get(ctx context.Context, key string) (string, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRedis_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRedis_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockRedis_Expecter) Get(ctx interface{}, key interface{}) *MockRedis_Get_Call {
	return &MockRedis_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockRedis_Get_Call) Run(run func(ctx context.Context, key string)) *MockRedis_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRedis_Get_Call) Return(s string, err error) *MockRedis_Get_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockRedis_Get_Call) RunAndReturn(run func(ctx context.Context, key string) (string, error)) *MockRedis_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockRedis
func (_mock *MockRedis) Set(ctx context.Context, key string, value interface{}, expiration time.Duration) error {
	ret := _mock.Called(ctx, key, value, expiration)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, interface{}, time.Duration) error); ok {
		r0 = returnFunc(ctx, key, value, expiration)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRedis_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockRedis_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value interface{}
//   - expiration time.Duration
func (_e *MockRedis_Expecter) Set(ctx interface{}, key interface{}, value interface{}, expiration interface{}) *MockRedis_Set_Call {
	return &MockRedis_Set_Call{Call: _e.mock.On("Set", ctx, key, value, expiration)}
}

func (_c *MockRedis_Set_Call) Run(run func(ctx context.Context, key string, value interface{}, expiration time.Duration)) *MockRedis_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 interface{}
		if args[2] != nil {
			arg2 = args[2].(interface{})
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRedis_Set_Call) Return(err error) *MockRedis_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRedis_Set_Call) RunAndReturn(run func(ctx context.Context, key string, value interface{}, expiration time.Duration) error) *MockRedis_Set_Call {
	_c.Call.Return(run)
	return _c
}

// TTL provides a mock function for the type MockRedis
func (_mock *MockRedis) TTL(ctx context.Context, key string) (time.Duration, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for TTL")
	}

	var r0 time.Duration
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (time.Duration, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) time.Duration); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRedis_TTL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TTL'
type MockRedis_TTL_Call struct {
	*mock.Call
}

// TTL is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockRedis_Expecter) TTL(ctx interface{}, key interface{}) *MockRedis_TTL_Call {
	return &MockRedis_TTL_Call{Call: _e.mock.On("TTL", ctx, key)}
}

func (_c *MockRedis_TTL_Call) Run(run func(ctx context.Context, key string)) *MockRedis_TTL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRedis_TTL_Call) Return(duration time.Duration, err error) *MockRedis_TTL_Call {
	_c.Call.Return(duration, err)
	return _c
}

func (_c *MockRedis_TTL_Call) RunAndReturn(run func(ctx context.Context, key string) (time.Duration, error)) *MockRedis_TTL_Call {
	_c.Call.Return(run)
	return _c
}
