@baseUrl = http://localhost:8080

### login
# @name login
POST {{baseUrl}}/api/v1/auth/login
Content-Type: application/json

{
    "email": "john.doe1@example.com",
    "password": "password"
}

### create user
POST {{baseUrl}}/api/v1/users
Content-Type: application/json
Authorization: Bearer {{login.response.body.data.access_token}}

{
    "name": "John Doe From Create User",
    "email": "john.doe.from.create.user@example.com",
    "password": "password"
}