@baseUrl = http://localhost:8080

### login
# @name login
POST {{baseUrl}}/api/v1/auth/login
Content-Type: application/json

{
    "email": "john.doe1@example.com",
    "password": "password"
}

### delete user
DELETE {{baseUrl}}/api/v1/users/690e7b7c16fb4a89b9d32a9d
Authorization: Bearer {{login.response.body.data.access_token}}