@baseUrl = http://localhost:8080

### login
# @name login
POST {{baseUrl}}/api/v1/auth/login
Content-Type: application/json

{
    "email": "john.doe1@example.com",
    "password": "password"
}

### get user by id
GET {{baseUrl}}/api/v1/users/690e7b2416fb4a89b9d32a9b
Authorization: Bearer {{login.response.body.data.access_token}}