GET http://localhost:8080/api/v1/users/690d6123cd2f5c5623f8dc46
Authorization: Bearer eyJhbGciOiJkaXIiLCJjdHkiOiJKV1QiLCJlbmMiOiJBMjU2R0NNIiwidHlwIjoiSldUIn0..2lUFrKnp24RJtfk5.lba6FQoGkxAQjk00Fu066iO5NWyTS3DMRsTxNDoWahCjqqAzL6f9B_gOG9abrJdBe2DCjWIOJFry5fXo1aY5HhQJpT--IO8wXFaEKLQwBnqQXLD5gWPER_gYGpCJ8H5wxE-qkRUrb_ehoajRhATbgetzhNk4stILaUHODS-jx-JuBwOUn5jJBtq_N6ebntA1DQ.C9xUSLu3zr1GulKhOapMnA