@baseUrl = http://localhost:8080

### Register User 1
POST {{baseUrl}}/api/v1/auth/register
Content-Type: application/json

{
    "name": "John Doe 1",
    "email": "john.doe1@example.com",
    "password": "password",
    "confirm_password": "password"
}

### Register User 2
POST {{baseUrl}}/api/v1/auth/register
Content-Type: application/json

{
    "name": "John Doe 2",
    "email": "john.doe2@example.com",
    "password": "password",
    "confirm_password": "password"
}