// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"github.com/7-solutions/backend-challenge/internal/app/domain/entity"
	"github.com/gofiber/fiber/v2"
	mock "github.com/stretchr/testify/mock"
	"go.mongodb.org/mongo-driver/v2/bson"
	"go.mongodb.org/mongo-driver/v2/mongo"
)

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) CreateUser(c *fiber.Ctx, user *entity.User) error {
	ret := _mock.Called(c, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*fiber.Ctx, *entity.User) error); ok {
		r0 = returnFunc(c, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUserRepository_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - c *fiber.Ctx
//   - user *entity.User
func (_e *MockUserRepository_Expecter) CreateUser(c interface{}, user interface{}) *MockUserRepository_CreateUser_Call {
	return &MockUserRepository_CreateUser_Call{Call: _e.mock.On("CreateUser", c, user)}
}

func (_c *MockUserRepository_CreateUser_Call) Run(run func(c *fiber.Ctx, user *entity.User)) *MockUserRepository_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *fiber.Ctx
		if args[0] != nil {
			arg0 = args[0].(*fiber.Ctx)
		}
		var arg1 *entity.User
		if args[1] != nil {
			arg1 = args[1].(*entity.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_CreateUser_Call) Return(err error) *MockUserRepository_CreateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_CreateUser_Call) RunAndReturn(run func(c *fiber.Ctx, user *entity.User) error) *MockUserRepository_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllPaginated provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) FindAllPaginated(c *fiber.Ctx, filter bson.M, sortField string, sortOrder int, page int, pageSize int) ([]*entity.User, bool, bool, error) {
	ret := _mock.Called(c, filter, sortField, sortOrder, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for FindAllPaginated")
	}

	var r0 []*entity.User
	var r1 bool
	var r2 bool
	var r3 error
	if returnFunc, ok := ret.Get(0).(func(*fiber.Ctx, bson.M, string, int, int, int) ([]*entity.User, bool, bool, error)); ok {
		return returnFunc(c, filter, sortField, sortOrder, page, pageSize)
	}
	if returnFunc, ok := ret.Get(0).(func(*fiber.Ctx, bson.M, string, int, int, int) []*entity.User); ok {
		r0 = returnFunc(c, filter, sortField, sortOrder, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*fiber.Ctx, bson.M, string, int, int, int) bool); ok {
		r1 = returnFunc(c, filter, sortField, sortOrder, page, pageSize)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(*fiber.Ctx, bson.M, string, int, int, int) bool); ok {
		r2 = returnFunc(c, filter, sortField, sortOrder, page, pageSize)
	} else {
		r2 = ret.Get(2).(bool)
	}
	if returnFunc, ok := ret.Get(3).(func(*fiber.Ctx, bson.M, string, int, int, int) error); ok {
		r3 = returnFunc(c, filter, sortField, sortOrder, page, pageSize)
	} else {
		r3 = ret.Error(3)
	}
	return r0, r1, r2, r3
}

// MockUserRepository_FindAllPaginated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllPaginated'
type MockUserRepository_FindAllPaginated_Call struct {
	*mock.Call
}

// FindAllPaginated is a helper method to define mock.On call
//   - c *fiber.Ctx
//   - filter bson.M
//   - sortField string
//   - sortOrder int
//   - page int
//   - pageSize int
func (_e *MockUserRepository_Expecter) FindAllPaginated(c interface{}, filter interface{}, sortField interface{}, sortOrder interface{}, page interface{}, pageSize interface{}) *MockUserRepository_FindAllPaginated_Call {
	return &MockUserRepository_FindAllPaginated_Call{Call: _e.mock.On("FindAllPaginated", c, filter, sortField, sortOrder, page, pageSize)}
}

func (_c *MockUserRepository_FindAllPaginated_Call) Run(run func(c *fiber.Ctx, filter bson.M, sortField string, sortOrder int, page int, pageSize int)) *MockUserRepository_FindAllPaginated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *fiber.Ctx
		if args[0] != nil {
			arg0 = args[0].(*fiber.Ctx)
		}
		var arg1 bson.M
		if args[1] != nil {
			arg1 = args[1].(bson.M)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		var arg5 int
		if args[5] != nil {
			arg5 = args[5].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockUserRepository_FindAllPaginated_Call) Return(users []*entity.User, b bool, b1 bool, err error) *MockUserRepository_FindAllPaginated_Call {
	_c.Call.Return(users, b, b1, err)
	return _c
}

func (_c *MockUserRepository_FindAllPaginated_Call) RunAndReturn(run func(c *fiber.Ctx, filter bson.M, sortField string, sortOrder int, page int, pageSize int) ([]*entity.User, bool, bool, error)) *MockUserRepository_FindAllPaginated_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEmail provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) FindByEmail(c *fiber.Ctx, email string, user *entity.User) error {
	ret := _mock.Called(c, email, user)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*fiber.Ctx, string, *entity.User) error); ok {
		r0 = returnFunc(c, email, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type MockUserRepository_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - c *fiber.Ctx
//   - email string
//   - user *entity.User
func (_e *MockUserRepository_Expecter) FindByEmail(c interface{}, email interface{}, user interface{}) *MockUserRepository_FindByEmail_Call {
	return &MockUserRepository_FindByEmail_Call{Call: _e.mock.On("FindByEmail", c, email, user)}
}

func (_c *MockUserRepository_FindByEmail_Call) Run(run func(c *fiber.Ctx, email string, user *entity.User)) *MockUserRepository_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *fiber.Ctx
		if args[0] != nil {
			arg0 = args[0].(*fiber.Ctx)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *entity.User
		if args[2] != nil {
			arg2 = args[2].(*entity.User)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepository_FindByEmail_Call) Return(err error) *MockUserRepository_FindByEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_FindByEmail_Call) RunAndReturn(run func(c *fiber.Ctx, email string, user *entity.User) error) *MockUserRepository_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) FindByID(c *fiber.Ctx, filter bson.M, user *entity.User) error {
	ret := _mock.Called(c, filter, user)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*fiber.Ctx, bson.M, *entity.User) error); ok {
		r0 = returnFunc(c, filter, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockUserRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - c *fiber.Ctx
//   - filter bson.M
//   - user *entity.User
func (_e *MockUserRepository_Expecter) FindByID(c interface{}, filter interface{}, user interface{}) *MockUserRepository_FindByID_Call {
	return &MockUserRepository_FindByID_Call{Call: _e.mock.On("FindByID", c, filter, user)}
}

func (_c *MockUserRepository_FindByID_Call) Run(run func(c *fiber.Ctx, filter bson.M, user *entity.User)) *MockUserRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *fiber.Ctx
		if args[0] != nil {
			arg0 = args[0].(*fiber.Ctx)
		}
		var arg1 bson.M
		if args[1] != nil {
			arg1 = args[1].(bson.M)
		}
		var arg2 *entity.User
		if args[2] != nil {
			arg2 = args[2].(*entity.User)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepository_FindByID_Call) Return(err error) *MockUserRepository_FindByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_FindByID_Call) RunAndReturn(run func(c *fiber.Ctx, filter bson.M, user *entity.User) error) *MockUserRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCollection provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetCollection() *mongo.Collection {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCollection")
	}

	var r0 *mongo.Collection
	if returnFunc, ok := ret.Get(0).(func() *mongo.Collection); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.Collection)
		}
	}
	return r0
}

// MockUserRepository_GetCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCollection'
type MockUserRepository_GetCollection_Call struct {
	*mock.Call
}

// GetCollection is a helper method to define mock.On call
func (_e *MockUserRepository_Expecter) GetCollection() *MockUserRepository_GetCollection_Call {
	return &MockUserRepository_GetCollection_Call{Call: _e.mock.On("GetCollection")}
}

func (_c *MockUserRepository_GetCollection_Call) Run(run func()) *MockUserRepository_GetCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUserRepository_GetCollection_Call) Return(collection *mongo.Collection) *MockUserRepository_GetCollection_Call {
	_c.Call.Return(collection)
	return _c
}

func (_c *MockUserRepository_GetCollection_Call) RunAndReturn(run func() *mongo.Collection) *MockUserRepository_GetCollection_Call {
	_c.Call.Return(run)
	return _c
}

// GetFilter provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetFilter(filters map[string]interface{}) bson.M {
	ret := _mock.Called(filters)

	if len(ret) == 0 {
		panic("no return value specified for GetFilter")
	}

	var r0 bson.M
	if returnFunc, ok := ret.Get(0).(func(map[string]interface{}) bson.M); ok {
		r0 = returnFunc(filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(bson.M)
		}
	}
	return r0
}

// MockUserRepository_GetFilter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFilter'
type MockUserRepository_GetFilter_Call struct {
	*mock.Call
}

// GetFilter is a helper method to define mock.On call
//   - filters map[string]interface{}
func (_e *MockUserRepository_Expecter) GetFilter(filters interface{}) *MockUserRepository_GetFilter_Call {
	return &MockUserRepository_GetFilter_Call{Call: _e.mock.On("GetFilter", filters)}
}

func (_c *MockUserRepository_GetFilter_Call) Run(run func(filters map[string]interface{})) *MockUserRepository_GetFilter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 map[string]interface{}
		if args[0] != nil {
			arg0 = args[0].(map[string]interface{})
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserRepository_GetFilter_Call) Return(m bson.M) *MockUserRepository_GetFilter_Call {
	_c.Call.Return(m)
	return _c
}

func (_c *MockUserRepository_GetFilter_Call) RunAndReturn(run func(filters map[string]interface{}) bson.M) *MockUserRepository_GetFilter_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) UpdateUser(c *fiber.Ctx, userID bson.ObjectID, currentVersion int, updates bson.M) error {
	ret := _mock.Called(c, userID, currentVersion, updates)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*fiber.Ctx, bson.ObjectID, int, bson.M) error); ok {
		r0 = returnFunc(c, userID, currentVersion, updates)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockUserRepository_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - c *fiber.Ctx
//   - userID bson.ObjectID
//   - currentVersion int
//   - updates bson.M
func (_e *MockUserRepository_Expecter) UpdateUser(c interface{}, userID interface{}, currentVersion interface{}, updates interface{}) *MockUserRepository_UpdateUser_Call {
	return &MockUserRepository_UpdateUser_Call{Call: _e.mock.On("UpdateUser", c, userID, currentVersion, updates)}
}

func (_c *MockUserRepository_UpdateUser_Call) Run(run func(c *fiber.Ctx, userID bson.ObjectID, currentVersion int, updates bson.M)) *MockUserRepository_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *fiber.Ctx
		if args[0] != nil {
			arg0 = args[0].(*fiber.Ctx)
		}
		var arg1 bson.ObjectID
		if args[1] != nil {
			arg1 = args[1].(bson.ObjectID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 bson.M
		if args[3] != nil {
			arg3 = args[3].(bson.M)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUserRepository_UpdateUser_Call) Return(err error) *MockUserRepository_UpdateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_UpdateUser_Call) RunAndReturn(run func(c *fiber.Ctx, userID bson.ObjectID, currentVersion int, updates bson.M) error) *MockUserRepository_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}
